package com.br.itsingular.enums;

import lombok.Getter;

@Getter
public enum ClientesParceiros {

	BANCO_ABC, BANCO_MERCEDES_BENZ, BAZAR_DO_CONSORCIO, BLK, BMB, BMG, BRADESCO, CEA, CHUBB, DB1, 
	DPASCHOAL, EMBRACON, FOLHA_DE_SP, GLOBAL_HITSS, GLUCO_GEAR,IBM, IT_SINGULAR, LTM, MIMO, 
	ODONTOPREV, PORTAL_DE_DOCUMENTOS,PORTO_SEGURO,PRIME_IT, SAINT_GOBAN, SBT, TIVIT, TRANSFOLHA, 
	UNIGEL, VERTEM, WIPRO;

	private String clientes;

}
