package com.br.itsingular.enums;

import lombok.Getter;

@Getter
public enum TecnologiaPrincipal {
	
	ABAP, ANDROID, ANGULAR, BASIS, BI, BPM, BW, CSHARP, CISCO, CLOUD, COBOL, CRM, 
	CYBER_SECURITY, DATAPOWER, DBA, DELPHI, DEVOPS, DEVSECOPS, DOTNET, DOTNETCORE, EWM, FI_CO, FIORI, FORTIGATE, FSCD, HYBRIS, 
	IA, INFRAESTRUTURA, IONIC, JAVA, JAVASCRIPT, KOTLIN, LINUX, MIDDLEWARE, MYSQL, NODE, ORACLE, 
	PHP, PL_SQL, PMO, PROJETOS, PYTHON, REACT, REACT_NATIVE, REACT_JS, REQUISITOS, RUBY, SCRUM, SD, 
	SELENIUM, SQL, SWIFT, TESTES_AUTOMATIZADOS, TM, UX_UI, VB_NET, VMWARE, VTEX, VTEX_IO, WEB, 
	WEB_ANALYTICS, ZABBIX;
	
	private String tecnologiaPrincipal;
}
